---
  - name: Config Web VM with Docker
    hosts: webservers
    become: true
    tasks:
    - name: Uninstall Install apache httpd
      apt:
        name: apache2
        state: absent
    - name: docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present
    - name: install pip3
      apt:
        name: python3-pip
        state: present
    - name: install python docker module
      pip:
        name: docker
        state: present
    - name: enable docker service
      systemd:
        name: docker
        enabled: yes
    - name: download and launch a docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80
